import "./globals.css";
import {Inter} from "next/font/google"
import { ThemeProvider } from "next-themes";
import Header from "@/components/ui/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { dark , neobrutalism } from "@clerk/themes";
import { Html, Body, Main, Footer } from "next/document";



export const metadata = {
  title: "PROFAI - Ai Professor",
  description: "Generated by create next app"
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider suppressHydrationWarning appearance={{
      baseTheme: [dark],
    }}>
    <Html lang="en">
      <Body suppressHydrationWarning >
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {/* Header */}
            <Header/>

            {/* Main */}
            <Main className="min-h-screen">{children}</Main>

            {/* footer */}
            <Footer className="bg-muted/50 py-12">
              <div className="container mx-auto px-4 text-center text-gray-400">
                <p>Made by AURA</p>
              </div>
            </Footer>

          </ThemeProvider>
      </Body>
    </Html>
    </ClerkProvider>
  );
}
